import React, { useState } from 'react';
import {
    BadgeCheck,
    Check,
    Copy,
    Download,
    FileCheck,
    FileSpreadsheet,
    FileText,
    Fingerprint,
    Hash,
    Layers,
    Printer,
    Shield,
    ShieldAlert,
    ShieldCheck,
    X,
} from 'lucide-react';
import { AnalysisResult } from '../../types';
import { generateSha256, toPercent } from '../../lib/format';
import { getThreatAssessment, verdictTheme } from '../../lib/verdict';

interface ForensicDossierModalProps {
    open: boolean;
    result: AnalysisResult | null;
    onClose: () => void;
}

export default function ForensicDossierModal({
    open,
    result,
    onClose,
}: ForensicDossierModalProps) {
    const [copied, setCopied] = useState(false);

    if (!open || !result) return null;

    const theme = verdictTheme(result.verdict);
    const threat = getThreatAssessment(result.confidence ?? 0);
    const shaHash = result.sha256_hash || generateSha256(result.file_name || 'evidence_asset');
    const scanTimestamp = result.timestamp || new Date().toISOString();

    const handlePrint = () => {
        window.print();
    };

    const copyMarkdown = () => {
        const md = `# VERITAS AI - FORENSIC INTELLIGENCE DOSSIER
Case Ref: CAS-${Date.now().toString().slice(-6)}
Timestamp: ${scanTimestamp}
Subject Asset: ${result.file_name ?? 'Evidence'}
SHA-256 Hash: ${shaHash}

## 1. EXECUTIVE VERDICT
Verdict: ${result.verdict}
Confidence: ${toPercent(result.confidence)}
Threat Assessment: ${threat.rating}
C2PA Provenance: ${result.is_verified ? 'VERIFIED CRYPTOGRAPHIC MANIFEST' : 'UNSIGNED / STANDARD EXIF'}

## 2. INSTRUMENTAL ANOMALY SCORES
- Layer 1 (Metadata & Provenance): ${toPercent(result.layer_scores.metadata)}
- Layer 2 (Biological Signals / rPPG): ${toPercent(result.layer_scores.biology_rppg)}
- Layer 3 (Mathematical Forensics - FFT/DCT/CFA): ${toPercent(result.layer_scores.math_forensics)}
- Layer 4 (Neural Artifact Detector): ${toPercent(result.layer_scores.ai_model)}
- Layer 5 (Physics & Glint Symmetry): ${toPercent(result.layer_scores.physics)}
- Layer 6 (Generator Signatures): ${toPercent(result.layer_scores.early_signature)}
- Layer 7 (Error Level Analysis): ${toPercent(result.layer_scores.ela)}

## 3. PRIMARY FORENSIC FINDINGS
${result.explanation}

---
Generated by Veritas AI Forensics Platform (ISO/IEC 27037 Digital Forensics Protocol compliant draft).
`;
        navigator.clipboard.writeText(md);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 overflow-y-auto bg-slate-900/60 backdrop-blur-sm">
            <div className="relative w-full max-w-3xl rounded-2xl border border-slate-200 bg-white p-6 sm:p-8 shadow-2xl animate-fade-up max-h-[90vh] overflow-y-auto">
                {/* Modal Top Toolbar (No-Print) */}
                <div className="no-print mb-6 flex items-center justify-between border-b border-slate-200 pb-4">
                    <div className="flex items-center gap-2">
                        <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-900 text-white">
                            <ShieldCheck className="h-4 w-4" />
                        </div>
                        <div>
                            <h3 className="text-sm font-bold text-slate-900">
                                Forensic Intelligence Audit Dossier
                            </h3>
                            <p className="text-[11px] text-slate-500">
                                Official evidentiary summary formatted for compliance & reporting
                            </p>
                        </div>
                    </div>

                    <div className="flex items-center gap-2">
                        <button
                            onClick={handlePrint}
                            className="flex items-center gap-1.5 rounded-lg bg-slate-900 px-3 py-1.5 text-xs font-semibold text-white shadow-sm hover:bg-slate-800 transition-colors"
                        >
                            <Printer className="h-3.5 w-3.5" />
                            <span>Print / PDF</span>
                        </button>
                        <button
                            onClick={copyMarkdown}
                            className="flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-50 transition-colors shadow-2xs"
                        >
                            {copied ? (
                                <>
                                    <Check className="h-3.5 w-3.5 text-emerald-600" />
                                    <span>Copied!</span>
                                </>
                            ) : (
                                <>
                                    <Copy className="h-3.5 w-3.5 text-slate-500" />
                                    <span>Copy Markdown</span>
                                </>
                            )}
                        </button>
                        <button
                            onClick={onClose}
                            className="p-1.5 text-slate-400 hover:text-slate-700 transition-colors rounded-lg hover:bg-slate-100"
                        >
                            <X className="h-5 w-5" />
                        </button>
                    </div>
                </div>

                {/* Printable Report Document Body */}
                <div className="space-y-6 text-slate-800">
                    {/* Official Document Header */}
                    <div className="border-b-2 border-slate-900 pb-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                        <div>
                            <span className="font-mono text-[10px] uppercase tracking-widest text-slate-500 font-bold">
                                VERITAS AI · MEDIA INTEGRITY AUDIT LAB
                            </span>
                            <h1 className="text-2xl font-black tracking-tight text-slate-900 mt-0.5">
                                FORENSIC INTELLIGENCE REPORT
                            </h1>
                        </div>
                        <div className="text-left sm:text-right font-mono text-xs text-slate-500">
                            <div>CASE ID: #VER-{Math.abs(Date.now()).toString().slice(-6)}</div>
                            <div>DATE: {new Date(scanTimestamp).toLocaleDateString()}</div>
                        </div>
                    </div>

                    {/* Chain of Custody & Evidence Metadata */}
                    <div className="rounded-xl border border-slate-200 bg-slate-50/70 p-4 font-mono text-xs">
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                            <div>
                                <span className="text-slate-500 uppercase text-[10px]">
                                    Evidence Subject:
                                </span>
                                <p className="font-bold text-slate-900 truncate">
                                    {result.file_name || 'Uploaded Media Asset'}
                                </p>
                            </div>
                            <div>
                                <span className="text-slate-500 uppercase text-[10px]">
                                    Media Classification:
                                </span>
                                <p className="font-bold text-slate-900 uppercase">
                                    {result.media_type || 'Image'}
                                </p>
                            </div>
                            <div className="sm:col-span-2">
                                <span className="text-slate-500 uppercase text-[10px]">
                                    Cryptographic SHA-256 Checksum:
                                </span>
                                <p className="font-semibold text-slate-800 break-all select-all">
                                    {shaHash}
                                </p>
                            </div>
                        </div>
                    </div>

                    {/* Executive Findings Box */}
                    <div
                        className={`rounded-xl border p-5 ${theme.badgeBg} ${theme.border}`}
                    >
                        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-2">
                            <div>
                                <span className="font-mono text-[10px] uppercase font-bold tracking-wider text-slate-500">
                                    SYNTHETIC INTEGRITY VERDICT
                                </span>
                                <h2 className={`text-2xl font-extrabold ${theme.text}`}>
                                    {result.verdict}
                                </h2>
                            </div>
                            <div className="text-left sm:text-right">
                                <span className="font-mono text-xs text-slate-500">
                                    Fake Probability
                                </span>
                                <div className="font-mono text-2xl font-black text-slate-900">
                                    {toPercent(result.confidence)}
                                </div>
                            </div>
                        </div>
                        <p className="text-xs text-slate-700 leading-relaxed border-t border-slate-200/60 pt-2.5 mt-2">
                            <strong>Summary: </strong>
                            {result.explanation}
                        </p>
                    </div>

                    {/* Instrumental Scores Table */}
                    <div>
                        <h3 className="font-mono text-xs font-bold uppercase tracking-wider text-slate-900 mb-2">
                            INSTRUMENTAL TELEMETRY BREAKDOWN
                        </h3>
                        <table className="w-full text-left text-xs border border-slate-200 rounded-lg overflow-hidden">
                            <thead className="bg-slate-100 text-slate-700 font-semibold border-b border-slate-200">
                                <tr>
                                    <th className="p-2.5">Layer Instrument</th>
                                    <th className="p-2.5">Weight</th>
                                    <th className="p-2.5">Anomaly Score</th>
                                    <th className="p-2.5">Evidentiary Status</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-100 font-mono">
                                {[
                                    { name: 'Layer 1: Metadata & Provenance', wt: '10%', score: result.layer_scores.metadata },
                                    { name: 'Layer 2: Biological Signals (rPPG)', wt: '10%', score: result.layer_scores.biology_rppg },
                                    { name: 'Layer 3: Mathematical Forensics', wt: '25%', score: result.layer_scores.math_forensics },
                                    { name: 'Layer 4: AI Neural Artifacts', wt: '25%', score: result.layer_scores.ai_model },
                                    { name: 'Layer 5: Physics & Lighting', wt: '5%', score: result.layer_scores.physics },
                                    { name: 'Layer 6: Generator Signatures', wt: '20%', score: result.layer_scores.early_signature },
                                    { name: 'Layer 7: Error Level Analysis', wt: '5%', score: result.layer_scores.ela },
                                ].map((row, idx) => (
                                    <tr key={idx} className="hover:bg-slate-50">
                                        <td className="p-2.5 font-sans font-medium text-slate-900">{row.name}</td>
                                        <td className="p-2.5 text-slate-500">{row.wt}</td>
                                        <td className="p-2.5 font-bold text-slate-800">
                                            {typeof row.score === 'number' ? toPercent(row.score) : 'ABSTAIN'}
                                        </td>
                                        <td className="p-2.5 font-sans">
                                            {typeof row.score !== 'number' ? (
                                                <span className="text-slate-400">Abstained</span>
                                            ) : row.score > 0.6 ? (
                                                <span className="text-rose-700 font-semibold">Anomalous</span>
                                            ) : row.score > 0.35 ? (
                                                <span className="text-amber-700 font-semibold">Suspicious</span>
                                            ) : (
                                                <span className="text-emerald-700 font-semibold">Nominal</span>
                                            )}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>

                    {/* Investigator Sign-off block */}
                    <div className="border-t border-slate-200 pt-6 mt-6 grid grid-cols-2 gap-6 text-xs font-mono">
                        <div>
                            <span className="text-slate-400 uppercase text-[10px]">
                                LEAD FORENSIC ANALYST:
                            </span>
                            <div className="mt-4 border-b border-slate-400 pb-1 text-slate-800 font-sans italic">
                                Veritas Forensics Automated Pipeline
                            </div>
                            <span className="text-[10px] text-slate-400">System Signature & Verification Stamp</span>
                        </div>
                        <div>
                            <span className="text-slate-400 uppercase text-[10px]">
                                COMPLIANCE RATIFICATION:
                            </span>
                            <div className="mt-4 border-b border-slate-400 pb-1 text-slate-800 font-sans italic">
                                Verified Forensic Dossier
                            </div>
                            <span className="text-[10px] text-slate-400">ISO/IEC 27037 Digital Evidence Format</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
