import React, { useState } from 'react';
import {
    Activity,
    ChevronDown,
    ChevronUp,
    Cpu,
    FileSearch,
    Fingerprint,
    Info,
    Lightbulb,
    Ruler,
    Waves,
} from 'lucide-react';
import { AnalysisResult, LayerScores } from '../../types';
import { scoreBadgeColor, scoreColor, scoreTextColor } from '../../lib/verdict';

interface LayerMeta {
    key: keyof LayerScores;
    label: string;
    icon: React.ReactNode;
    weight: string;
    blurb: string;
    description: string;
    thresholds: string;
}

const LAYERS: LayerMeta[] = [
    {
        key: 'metadata',
        label: 'Layer 1 · Metadata & Provenance',
        icon: <FileSearch className="h-4 w-4" />,
        weight: '10%',
        blurb: 'EXIF structure · Header magic numbers · C2PA signatures',
        description:
            'Inspects file header bitstream integrity, EXIF tag richness, camera serial profiles, and editing software signatures. Verified C2PA Content Credentials immediately override heuristics.',
        thresholds: 'Anomalies flagged if EXIF tag count < 5 or software tags indicate editing suites.',
    },
    {
        key: 'biology_rppg',
        label: 'Layer 2 · Biological Signals (rPPG)',
        icon: <Activity className="h-4 w-4" />,
        weight: '10%',
        blurb: 'CHROM rPPG chrominance · Cardiac pulse (0.7–4.0 Hz)',
        description:
            'Extracts sub-surface hemoglobin absorption fluctuations from facial skin across consecutive video frames using chrominance-based rPPG. Evaluates physiological signal consistency.',
        thresholds: 'Flatline pulse wave or absent cardiac peak (0.7–4.0 Hz) scores as high synthetic probability.',
    },
    {
        key: 'math_forensics',
        label: 'Layer 3 · Mathematical Forensics',
        icon: <Ruler className="h-4 w-4" />,
        weight: '25%',
        blurb: '2D FFT spectral grid · DCT coefficients · CFA Bayer mosaic',
        description:
            'Performs Fourier and Discrete Cosine Transforms to expose periodic high-frequency grid artifacts. Inspects Color Filter Array (CFA) Bayer mosaic traces naturally left by physical camera sensors.',
        thresholds: 'Absence of camera CFA mosaic or abnormal DCT blockiness indicates RGB synthesis.',
    },
    {
        key: 'ai_model',
        label: 'Layer 4 · AI Artifact Detector',
        icon: <Cpu className="h-4 w-4" />,
        weight: '25%',
        blurb: 'Pretrained neural classifier / Statistical blur & entropy fallback',
        description:
            'Employs a deep neural transformer or deterministic statistical heuristic measuring spatial entropy, blur gradient dispersion, and chromatic histogram anomalies.',
        thresholds: 'Threshold calibrated at 0.75+ for synthetic texture classification.',
    },
    {
        key: 'physics',
        label: 'Layer 5 · Physics & Lighting',
        icon: <Lightbulb className="h-4 w-4" />,
        weight: '5%',
        blurb: 'Quadrant illumination vector · Corneal catchlight symmetry',
        description:
            'Analyzes the primary illumination gradient across 4 image quadrants and checks mirror symmetry of specular reflection catchlights in the subject’s eyes.',
        thresholds: 'Catchlight angular discrepancy > 25° or quadrant flux inversion flags manipulation.',
    },
    {
        key: 'early_signature',
        label: 'Layer 6 · Generator Signatures',
        icon: <Fingerprint className="h-4 w-4" />,
        weight: '20%',
        blurb: 'High-frequency spectral peaks · Up-sampling grid traces',
        description:
            'Detects regular periodic frequency spikes generated by transposed convolution and bilinear upsampling layers commonly present in GANs and Diffusion architectures.',
        thresholds: 'Calibrated divisor triggers when spectral peak count > 5.',
    },
    {
        key: 'ela',
        label: 'Layer 7 · Error Level Analysis',
        icon: <Waves className="h-4 w-4" />,
        weight: '5%',
        blurb: 'JPEG re-quantization difference · Splice boundary glow',
        description:
            'Re-compresses the image at calibrated 95% quality to measure local compression error deviation. Inconsistent error levels expose spliced elements or localized editing.',
        thresholds: 'Variance standard deviation > 0.4 indicates multi-source compression history.',
    },
];

const SEGMENTS = 20;

function getLayerSubmetrics(result: AnalysisResult, key: keyof LayerScores): Array<{ label: string; value: string }> {
    const d = result.details || {};
    switch (key) {
        case 'metadata': {
            const meta = d.metadata || {};
            return [
                { label: 'EXIF Count', value: meta.exif_count !== undefined ? `${meta.exif_count} tags` : 'None' },
                { label: 'Camera', value: meta.camera_model ? `${meta.camera_make || ''} ${meta.camera_model}` : 'Unknown / Stripped' },
                { label: 'Software', value: meta.software ? String(meta.software) : 'None' },
            ];
        }
        case 'biology_rppg': {
            const bio = d.biology || {};
            const band = bio.pulse_band;
            return [
                { label: 'Detected BPM', value: band?.detected && band.estimated_bpm ? `~${band.estimated_bpm} BPM` : 'No pulse' },
                { label: 'Frames Tested', value: `${bio.face_frames ?? 1} frames` },
                { label: 'Signal SNR', value: band?.snr ? `${band.snr.toFixed(1)} dB` : 'N/A' },
            ];
        }
        case 'math_forensics': {
            const m = d.math || {};
            return [
                { label: 'FFT Grid Score', value: typeof m.fft_score === 'number' ? `${(m.fft_score * 100).toFixed(0)}%` : 'N/A' },
                { label: 'DCT Residue', value: typeof m.dct_score === 'number' ? `${(m.dct_score * 100).toFixed(0)}%` : 'N/A' },
                { label: 'CFA Absence', value: typeof m.cfa_absence_score === 'number' ? `${(m.cfa_absence_score * 100).toFixed(0)}%` : 'N/A' },
            ];
        }
        case 'ai_model': {
            const ai = d.ai_model || {};
            return [
                { label: 'Inference Engine', value: ai.method === 'pretrained' ? 'Neural Transformer' : 'Heuristic' },
                { label: 'Spatial Entropy', value: typeof ai.entropy_score === 'number' ? `${(ai.entropy_score * 100).toFixed(0)}%` : 'N/A' },
                { label: 'Blur Gradient', value: typeof ai.blur_score === 'number' ? `${(ai.blur_score * 100).toFixed(0)}%` : 'N/A' },
            ];
        }
        case 'physics': {
            const p = d.physics || {};
            return [
                { label: 'Lighting Flux', value: p.lighting?.score ? `${(p.lighting.score * 100).toFixed(0)}%` : 'Consistent' },
                { label: 'Glint Error', value: p.eye_glint?.symmetry_error ? `${(p.eye_glint.symmetry_error * 100).toFixed(0)}%` : 'Normal' },
            ];
        }
        case 'early_signature': {
            const sig = d.early_signature || {};
            return [
                { label: 'Spectral Peaks', value: sig.fft_peaks !== undefined ? `${sig.fft_peaks} spikes` : 'None' },
                { label: 'High-Freq Energy', value: sig.fft_high_freq_mean ? `${(sig.fft_high_freq_mean * 100).toFixed(0)}%` : 'Normal' },
            ];
        }
        case 'ela': {
            const ela = d.ela || {};
            return [
                { label: 'Avg Brightness', value: ela.avg_ela_brightness ? `${ela.avg_ela_brightness.toFixed(1)} px` : 'Normal' },
                { label: 'Error Std Dev', value: ela.ela_brightness_std ? `${ela.ela_brightness_std.toFixed(2)}` : 'Uniform' },
            ];
        }
        default:
            return [];
    }
}

interface LayerGridProps {
    result: AnalysisResult;
}

export default function LayerGrid({ result }: LayerGridProps) {
    const [expandedLayer, setExpandedLayer] = useState<string | null>(null);

    const toggleExpand = (key: string) => {
        setExpandedLayer((prev) => (prev === key ? null : key));
    };

    const activeCount = Object.keys(result.layer_scores || {}).length;

    return (
        <section className="panel animate-fade-up overflow-hidden border-slate-200/90 bg-white">
            {/* Header */}
            <div className="flex items-center justify-between border-b border-slate-200/80 px-5 py-4 bg-slate-50/50">
                <div className="flex items-center gap-2">
                    <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-100 text-indigo-700">
                        <Cpu className="h-4 w-4" />
                    </div>
                    <div>
                        <h3 className="text-sm font-bold text-slate-900">
                            7-Layer Forensic Instrumentation Matrix
                        </h3>
                        <p className="text-[11px] text-slate-500">
                            Multi-domain anomaly signals weighted by evidentiary significance
                        </p>
                    </div>
                </div>

                <div className="flex items-center gap-2">
                    <span className="rounded-full bg-slate-100 px-3 py-1 font-mono text-xs font-semibold text-slate-700 border border-slate-200">
                        {activeCount}/7 Active Instruments
                    </span>
                </div>
            </div>

            {/* Layer Rows */}
            <div className="divide-y divide-slate-100">
                {LAYERS.map((layer, i) => {
                    const layerKey = String(layer.key);
                    const raw = result.layer_scores[layer.key];
                    const abstained = typeof raw !== 'number';
                    const score = abstained ? 0 : raw;
                    const isExpanded = expandedLayer === layerKey;
                    const submetrics = getLayerSubmetrics(result, layer.key);
                    const litSegments = Math.round(score * SEGMENTS);

                    return (
                        <div key={layerKey} className="transition-colors hover:bg-slate-50/70">
                            <div
                                onClick={() => toggleExpand(layerKey)}
                                className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 p-4 sm:px-5 cursor-pointer select-none"
                            >
                                {/* Layer Title & Icon */}
                                <div className="flex items-center gap-3 min-w-0 sm:w-64">
                                    <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-slate-200 bg-slate-50 text-sky-700 shadow-2xs">
                                        {layer.icon}
                                    </div>
                                    <div className="min-w-0">
                                        <div className="flex items-center gap-2">
                                            <p className="truncate text-xs font-bold text-slate-900">
                                                {layer.label}
                                            </p>
                                            <span className="rounded bg-slate-100 px-1.5 py-0.2 font-mono text-[9px] font-medium text-slate-500">
                                                wt: {layer.weight}
                                            </span>
                                        </div>
                                        <p className="truncate text-[11px] text-slate-500 mt-0.5">
                                            {layer.blurb}
                                        </p>
                                    </div>
                                </div>

                                {/* Segmented Bar */}
                                <div className="hidden md:flex flex-1 items-center gap-[3px] px-4">
                                    {Array.from({ length: SEGMENTS }, (_, s) => (
                                        <span
                                            key={s}
                                            className={`h-2.5 flex-1 rounded-[2px] transition-colors duration-200 ${
                                                !abstained && s < litSegments
                                                    ? scoreColor(score)
                                                    : 'bg-slate-200/70'
                                            }`}
                                        />
                                    ))}
                                </div>

                                {/* Mobile bar */}
                                <div className="block md:hidden w-full">
                                    <div className="h-1.5 w-full rounded-full bg-slate-100 overflow-hidden">
                                        {!abstained && (
                                            <div
                                                className={`h-full rounded-full ${scoreColor(score)}`}
                                                style={{ width: `${Math.max(score * 100, 3)}%` }}
                                            />
                                        )}
                                    </div>
                                </div>

                                {/* Score & Expand trigger */}
                                <div className="flex items-center justify-between sm:justify-end gap-3 sm:w-32">
                                    <div className="text-right">
                                        {abstained ? (
                                            <span className="rounded bg-slate-100 px-2 py-0.5 font-mono text-[11px] font-semibold text-slate-400">
                                                ABSTAINED
                                            </span>
                                        ) : (
                                            <span
                                                className={`inline-flex items-center rounded-md px-2 py-0.5 font-mono text-xs font-bold border ${scoreBadgeColor(
                                                    score
                                                )}`}
                                            >
                                                {(score * 100).toFixed(1)}%
                                            </span>
                                        )}
                                    </div>
                                    <button
                                        onClick={(e) => {
                                            e.stopPropagation();
                                            toggleExpand(layerKey);
                                        }}
                                        className="text-slate-400 hover:text-slate-700 p-1"
                                    >
                                        {isExpanded ? (
                                            <ChevronUp className="h-4 w-4" />
                                        ) : (
                                            <ChevronDown className="h-4 w-4" />
                                        )}
                                    </button>
                                </div>
                            </div>

                            {/* Expandable Drilldown details */}
                            {isExpanded && (
                                <div className="border-t border-slate-100 bg-slate-50/70 px-5 py-4 text-xs animate-fade-up">
                                    <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-3">
                                        {submetrics.map((sub, idx) => (
                                            <div
                                                key={idx}
                                                className="rounded-lg border border-slate-200 bg-white p-2.5 shadow-2xs"
                                            >
                                                <span className="micro-label !text-slate-400">
                                                    {sub.label}
                                                </span>
                                                <p className="mt-0.5 font-mono text-xs font-semibold text-slate-800">
                                                    {sub.value}
                                                </p>
                                            </div>
                                        ))}
                                    </div>

                                    <div className="rounded-lg border border-slate-200/80 bg-white p-3 space-y-1.5">
                                        <p className="text-slate-700 leading-relaxed">
                                            <strong className="font-semibold text-slate-900">
                                                Scientific Rationale:{' '}
                                            </strong>
                                            {layer.description}
                                        </p>
                                        <p className="text-slate-500 font-mono text-[11px]">
                                            <strong>Threshold Rule: </strong>
                                            {layer.thresholds}
                                        </p>
                                    </div>
                                </div>
                            )}
                        </div>
                    );
                })}
            </div>
        </section>
    );
}
